//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBLocalization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MSBStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSBStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xamarin.iOS.Tasks.Core.MSBStrings", typeof(MSBStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string M0001 {
            get {
                return ResourceManager.GetString("M0001", resourceCulture);
            }
        }
        
        internal static string M0002 {
            get {
                return ResourceManager.GetString("M0002", resourceCulture);
            }
        }
        
        internal static string E0003 {
            get {
                return ResourceManager.GetString("E0003", resourceCulture);
            }
        }
        
        internal static string E0004 {
            get {
                return ResourceManager.GetString("E0004", resourceCulture);
            }
        }
        
        internal static string E0005 {
            get {
                return ResourceManager.GetString("E0005", resourceCulture);
            }
        }
        
        internal static string E0006 {
            get {
                return ResourceManager.GetString("E0006", resourceCulture);
            }
        }
        
        internal static string E0007 {
            get {
                return ResourceManager.GetString("E0007", resourceCulture);
            }
        }
        
        internal static string E0008 {
            get {
                return ResourceManager.GetString("E0008", resourceCulture);
            }
        }
        
        internal static string E0009 {
            get {
                return ResourceManager.GetString("E0009", resourceCulture);
            }
        }
        
        internal static string E0010 {
            get {
                return ResourceManager.GetString("E0010", resourceCulture);
            }
        }
        
        internal static string E0011 {
            get {
                return ResourceManager.GetString("E0011", resourceCulture);
            }
        }
        
        internal static string E0012 {
            get {
                return ResourceManager.GetString("E0012", resourceCulture);
            }
        }
        
        internal static string E0013 {
            get {
                return ResourceManager.GetString("E0013", resourceCulture);
            }
        }
        
        internal static string E0014 {
            get {
                return ResourceManager.GetString("E0014", resourceCulture);
            }
        }
        
        internal static string E0015 {
            get {
                return ResourceManager.GetString("E0015", resourceCulture);
            }
        }
        
        internal static string W0016 {
            get {
                return ResourceManager.GetString("W0016", resourceCulture);
            }
        }
        
        internal static string M0017 {
            get {
                return ResourceManager.GetString("M0017", resourceCulture);
            }
        }
        
        internal static string M0018 {
            get {
                return ResourceManager.GetString("M0018", resourceCulture);
            }
        }
        
        internal static string W0019 {
            get {
                return ResourceManager.GetString("W0019", resourceCulture);
            }
        }
        
        internal static string W0020 {
            get {
                return ResourceManager.GetString("W0020", resourceCulture);
            }
        }
        
        internal static string W0021 {
            get {
                return ResourceManager.GetString("W0021", resourceCulture);
            }
        }
        
        internal static string W0022 {
            get {
                return ResourceManager.GetString("W0022", resourceCulture);
            }
        }
        
        internal static string E0023 {
            get {
                return ResourceManager.GetString("E0023", resourceCulture);
            }
        }
        
        internal static string E0024 {
            get {
                return ResourceManager.GetString("E0024", resourceCulture);
            }
        }
        
        internal static string E0025 {
            get {
                return ResourceManager.GetString("E0025", resourceCulture);
            }
        }
        
        internal static string E0026 {
            get {
                return ResourceManager.GetString("E0026", resourceCulture);
            }
        }
        
        internal static string E0027 {
            get {
                return ResourceManager.GetString("E0027", resourceCulture);
            }
        }
        
        internal static string E0028 {
            get {
                return ResourceManager.GetString("E0028", resourceCulture);
            }
        }
        
        internal static string E0029 {
            get {
                return ResourceManager.GetString("E0029", resourceCulture);
            }
        }
        
        internal static string E0030 {
            get {
                return ResourceManager.GetString("E0030", resourceCulture);
            }
        }
        
        internal static string E0031 {
            get {
                return ResourceManager.GetString("E0031", resourceCulture);
            }
        }
        
        internal static string E0032 {
            get {
                return ResourceManager.GetString("E0032", resourceCulture);
            }
        }
        
        internal static string E0033 {
            get {
                return ResourceManager.GetString("E0033", resourceCulture);
            }
        }
        
        internal static string W0034 {
            get {
                return ResourceManager.GetString("W0034", resourceCulture);
            }
        }
        
        internal static string E0035 {
            get {
                return ResourceManager.GetString("E0035", resourceCulture);
            }
        }
        
        internal static string E0036 {
            get {
                return ResourceManager.GetString("E0036", resourceCulture);
            }
        }
        
        internal static string E0037 {
            get {
                return ResourceManager.GetString("E0037", resourceCulture);
            }
        }
        
        internal static string E0038 {
            get {
                return ResourceManager.GetString("E0038", resourceCulture);
            }
        }
        
        internal static string E0039 {
            get {
                return ResourceManager.GetString("E0039", resourceCulture);
            }
        }
        
        internal static string E0040 {
            get {
                return ResourceManager.GetString("E0040", resourceCulture);
            }
        }
        
        internal static string E0041 {
            get {
                return ResourceManager.GetString("E0041", resourceCulture);
            }
        }
        
        internal static string E0042 {
            get {
                return ResourceManager.GetString("E0042", resourceCulture);
            }
        }
        
        internal static string E0043 {
            get {
                return ResourceManager.GetString("E0043", resourceCulture);
            }
        }
        
        internal static string E0044 {
            get {
                return ResourceManager.GetString("E0044", resourceCulture);
            }
        }
        
        internal static string E0045 {
            get {
                return ResourceManager.GetString("E0045", resourceCulture);
            }
        }
        
        internal static string E0046 {
            get {
                return ResourceManager.GetString("E0046", resourceCulture);
            }
        }
        
        internal static string M0047 {
            get {
                return ResourceManager.GetString("M0047", resourceCulture);
            }
        }
        
        internal static string E0048 {
            get {
                return ResourceManager.GetString("E0048", resourceCulture);
            }
        }
        
        internal static string E0049 {
            get {
                return ResourceManager.GetString("E0049", resourceCulture);
            }
        }
        
        internal static string E0050 {
            get {
                return ResourceManager.GetString("E0050", resourceCulture);
            }
        }
        
        internal static string W0051 {
            get {
                return ResourceManager.GetString("W0051", resourceCulture);
            }
        }
        
        internal static string W0052 {
            get {
                return ResourceManager.GetString("W0052", resourceCulture);
            }
        }
        
        internal static string E0053 {
            get {
                return ResourceManager.GetString("E0053", resourceCulture);
            }
        }
        
        internal static string W0054 {
            get {
                return ResourceManager.GetString("W0054", resourceCulture);
            }
        }
        
        internal static string E0055 {
            get {
                return ResourceManager.GetString("E0055", resourceCulture);
            }
        }
        
        internal static string E0056 {
            get {
                return ResourceManager.GetString("E0056", resourceCulture);
            }
        }
        
        internal static string E0057 {
            get {
                return ResourceManager.GetString("E0057", resourceCulture);
            }
        }
        
        internal static string E0058 {
            get {
                return ResourceManager.GetString("E0058", resourceCulture);
            }
        }
        
        internal static string E0059 {
            get {
                return ResourceManager.GetString("E0059", resourceCulture);
            }
        }
        
        internal static string E0060 {
            get {
                return ResourceManager.GetString("E0060", resourceCulture);
            }
        }
        
        internal static string E0061 {
            get {
                return ResourceManager.GetString("E0061", resourceCulture);
            }
        }
        
        internal static string E0062 {
            get {
                return ResourceManager.GetString("E0062", resourceCulture);
            }
        }
        
        internal static string E0063 {
            get {
                return ResourceManager.GetString("E0063", resourceCulture);
            }
        }
        
        internal static string E0064 {
            get {
                return ResourceManager.GetString("E0064", resourceCulture);
            }
        }
        
        internal static string E0065 {
            get {
                return ResourceManager.GetString("E0065", resourceCulture);
            }
        }
        
        internal static string E0066 {
            get {
                return ResourceManager.GetString("E0066", resourceCulture);
            }
        }
        
        internal static string E0067 {
            get {
                return ResourceManager.GetString("E0067", resourceCulture);
            }
        }
        
        internal static string E0068 {
            get {
                return ResourceManager.GetString("E0068", resourceCulture);
            }
        }
        
        internal static string E0069 {
            get {
                return ResourceManager.GetString("E0069", resourceCulture);
            }
        }
        
        internal static string E0070 {
            get {
                return ResourceManager.GetString("E0070", resourceCulture);
            }
        }
        
        internal static string W0071 {
            get {
                return ResourceManager.GetString("W0071", resourceCulture);
            }
        }
        
        internal static string W0072 {
            get {
                return ResourceManager.GetString("W0072", resourceCulture);
            }
        }
        
        internal static string W0073 {
            get {
                return ResourceManager.GetString("W0073", resourceCulture);
            }
        }
        
        internal static string E7001 {
            get {
                return ResourceManager.GetString("E7001", resourceCulture);
            }
        }
        
        internal static string E7002 {
            get {
                return ResourceManager.GetString("E7002", resourceCulture);
            }
        }
        
        internal static string E7003 {
            get {
                return ResourceManager.GetString("E7003", resourceCulture);
            }
        }
        
        internal static string E7004 {
            get {
                return ResourceManager.GetString("E7004", resourceCulture);
            }
        }
        
        internal static string E7005 {
            get {
                return ResourceManager.GetString("E7005", resourceCulture);
            }
        }
        
        internal static string E7006 {
            get {
                return ResourceManager.GetString("E7006", resourceCulture);
            }
        }
        
        internal static string E7007 {
            get {
                return ResourceManager.GetString("E7007", resourceCulture);
            }
        }
        
        internal static string E7008 {
            get {
                return ResourceManager.GetString("E7008", resourceCulture);
            }
        }
        
        internal static string E7009 {
            get {
                return ResourceManager.GetString("E7009", resourceCulture);
            }
        }
        
        internal static string E7010 {
            get {
                return ResourceManager.GetString("E7010", resourceCulture);
            }
        }
    }
}
