using ObjCRuntime;
using Foundation;
using CoreFoundation;
using System;

namespace SystemExtenisons {
	[Static]
	partial interface Constants
	{
		[Mac (10, 15)]
		[Field ("OSSystemExtensionErrorDomain")]
		NSString OSSystemExtensionErrorDomain { get; }

		[Mac (10, 15)]
		[Field ("OSBundleUsageDescriptionKey")]
		NSString OSBundleUsageDescriptionKey { get; }

		[Mac (10, 15)]
		[Field ("NSSystemExtensionUsageDescriptionKey")]
		NSString NSSystemExtensionUsageDescriptionKey { get; }
	}


	[Mac (10,15)]
	[BaseType (typeof(NSObject))]
	interface OSSystemExtensionRequest
	{
		[Static]
		[Export ("activationRequestForExtension:queue:")]
		OSSystemExtensionRequest ActivationRequestForExtension (string identifier, DispatchQueue queue);

		[Static]
		[Export ("deactivationRequestForExtension:queue:")]
		OSSystemExtensionRequest DeactivationRequestForExtension (string identifier, DispatchQueue queue);

		[Wrap ("WeakDelegate")]
		[NullAllowed]
		OSSystemExtensionRequestDelegate Delegate { get; set; }

		[NullAllowed, Export ("delegate", ArgumentSemantic.Weak)]
		NSObject WeakDelegate { get; set; }

		[Export ("identifier")]
		string Identifier { get; }
	}

	[Mac (10,15)]
	[BaseType (typeof(NSObject))]
	interface OSSystemExtensionProperties
	{
		[Export ("URL", ArgumentSemantic.Strong)]
		NSUrl URL { get; }

		[Export ("bundleIdentifier", ArgumentSemantic.Strong)]
		string BundleIdentifier { get; }

		[Export ("bundleVersion", ArgumentSemantic.Strong)]
		string BundleVersion { get; }

		[Export ("bundleShortVersion", ArgumentSemantic.Strong)]
		string BundleShortVersion { get; }
	}

	[Mac (10,15)]
	[Protocol, Model (AutoGeneratedName = true)]
	[BaseType (typeof(NSObject))]
	interface OSSystemExtensionRequestDelegate
	{
		[Abstract]
		[Export ("request:actionForReplacingExtension:withExtension:")]
		OSSystemExtensionReplacementAction Request (OSSystemExtensionRequest request, OSSystemExtensionProperties existing, OSSystemExtensionProperties ext);

		[Abstract]
		[Export ("requestNeedsUserApproval:")]
		void RequestNeedsUserApproval (OSSystemExtensionRequest request);

		[Abstract]
		[Export ("request:didFinishWithResult:")]
		void Request (OSSystemExtensionRequest request, OSSystemExtensionRequestResult result);

		[Abstract]
		[Export ("request:didFailWithError:")]
		void Request (OSSystemExtensionRequest request, NSError error);
	}

	[Mac (10,15)]
	[BaseType (typeof(NSObject))]
	[DisableDefaultCtor]
	interface OSSystemExtensionManager
	{
		[Static]
		[Export ("sharedManager")]
		OSSystemExtensionManager SharedManager { get; }

		[Export ("submitRequest:")]
		void SubmitRequest (OSSystemExtensionRequest request);
	}

}

